/* eslint-disable */
// @ts-nocheck
/*
* This file is a generated Typescript file for GRPC Gateway, DO NOT MODIFY
*/

export enum Kind {
  LOCATION = "LOCATION",
  FEDERATION = "FEDERATION",
  CONTROLLER = "CONTROLLER",
  ROUTER = "ROUTER",
  ACCOUNT = "ACCOUNT",
  USER = "USER",
  SECURITY_GROUP = "SECURITY_GROUP",
  ROLE = "ROLE",
  ACL = "ACL",
  PROJECT = "PROJECT",
  WORKFLOW = "WORKFLOW",
  TASKLOG = "TASKLOG",
  TENANT = "TENANT",
  NETWORK = "NETWORK",
  SUBNET = "SUBNET",
  NODE = "NODE",
  ALERT = "ALERT",
  WEBHOOK = "WEBHOOK",
  MESSAGE = "MESSAGE",
  SYS_DATABASE = "SYS_DATABASE",
  SYS_DATASOURCE = "SYS_DATASOURCE",
}